apiVersion: apps/v1
kind: Deployment
metadata:
  # name: react-app-deployment
  name: admin-frontend-deployment
  labels:
    app: admin-frontend
spec:
  replicas: 1  # Adjust replicas as per your needs
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      labels:
        app: admin-frontend
    spec:
      containers:
      - name: admin-frontend
        image: remote123/whiteboxlearning:admin_app  # Use the image name you've chosen
        ports:
        - containerPort: 3000  # Port that the app is exposed on
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "200m"
          
---
apiVersion: v1
kind: Service
metadata:
  name: admin-frontend-service
spec:
  selector:
    app: admin-frontend
  ports:
    - protocol: TCP
      port: 80  # The port exposed externally
      targetPort: 3000  # The port that the container is listening on
  type: ClusterIP  # ClusterIP is correct for internal services with Ingress handling external access
